language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/spring-webservice/.m2/repository'
    - '$HOME/spring-webservice/.gradle'

before_install:
  - cd 'spring-webservice'
  - chmod +x './gradlew'

script: "./spring-webservice/gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - innersme@gmail.com
